version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8081:8080"
    depends_on:
      - traefik
    volumes:
      - keycloak_db:/opt/jboss/keycloak/standalone

  node-red:
    image: nodered/node-red:latest
    environment:
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=node-red
      - KEYCLOAK_CLIENT_SECRET=secret
    depends_on:
      - keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-red.rule=Host(`node-red.${DOMAIN}`)"
      - "traefik.http.routers.node-red.entrypoints=web"
      - "traefik.http.services.node-red.loadbalancer.server.port=1880"
      - "traefik.http.middlewares.node-red-auth.forwardauth.address=http://keycloak:8080/auth/realms/master/protocol/openid-connect/auth?client_id=node-red&response_type=code&scope=openid&state=xyz&redirect_uri=http://node-red:1880/auth/callback"
      - "traefik.http.middlewares.node-red-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.node-red-auth.forwardauth.authResponseHeaders=X-Auth-Request-User"
      # - "traefik.http.routers.keycloak-ja-${RANDOMTAG}.tls.certresolver=letsencrypt"
    volumes:
      - node_red_data:/data

volumes:
  node_red_data:
  keycloak_db: