version: '3.9'
services:
  squid: 
    image: robhaswell/squid-authenticated
    ports:
      - 22133:3128
    environment:
      - SQUID_USERNAME=${SQUID_USERNAME}
      - SQUID_PASSWORD=${SQUID_PASSWORD}
  chatgpt-ssr: 
    image: yidadaa/chatgpt-next-web
    ports:
      - 2288:3000
    environment:
      - OPENAI_API_KEY=${CHATGPT_KEY}
      - CODE=${CHATGPT_PASSWORD}
  vault: 
    image: hashicorp/vault
    ports:
      - 8200:8200
    volumes:
      - ${PWD}/vault.hcl:/vault/vault.hcl
      - vault_backup:/vault/backup
    entrypoint: vault server -config /vault/vault.hcl
  node-red:
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - node_red_data:/data
    environment:
      - NODE_RED_CREDENTIAL_SECRET=${NODE_RED_PASSWORD}
  
volumes:
  node_red_data:
  vault_backup:
