version: '3.9'
services:
  squid: 
    image: robhaswell/squid-authenticated
    ports:
      - 22133:3128
    environment:
      - SQUID_USERNAME=${SQUID_USERNAME}
      - SQUID_PASSWORD=${SQUID_PASSWORD}
  chatgpt-ssr: 
    image: yidadaa/chatgpt-next-web
    expose:
      - 3000
    networks:
      - workspace
    environment:
      - OPENAI_API_KEY=${CHATGPT_KEY}
      - CODE=${CHATGPT_PASSWORD}
      - VIRTUAL_HOST=chatgpt.${DOMAIN}
      - LETSENCRYPT_HOST=chatgpt.${DOMAIN}
  vault: 
    image: hashicorp/vault
    expose:
      - 8200
    networks:
      - workspace
    volumes:
      - ${PWD}/vault.hcl:/vault/vault.hcl:ro
      - vault_backup:/vault/backup:rw
    environment:
      - VIRTUAL_HOST=vault.${DOMAIN}
      - LETSENCRYPT_HOST=vault.${DOMAIN}
    entrypoint: vault server -config /vault/vault.hcl
  node-red:
    image: nodered/node-red
    expose:
      - 1880
    networks:
      - workspace
    volumes:
      - node_red_data:/data:rw
    environment:
      - NODE_RED_CREDENTIAL_SECRET=${NODE_RED_PASSWORD}
      - VIRTUAL_HOST=node-red.${DOMAIN}
      - LETSENCRYPT_HOST=node-red.${DOMAIN}
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - workspace
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DOMAIN=${DOMAIN}
  certification:
    image: nginxproxy/acme-companion
    networks:
      - workspace
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  
volumes:
  node_red_data:
  vault_backup:
  certs:
  vhost:
  html:
  acme:

networks:
  workspace:

