name: ReDeploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commmands on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd selfhosted-applications
          git pull --rebase
          source .env && docker compose up -d 
